//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.11 at 02:53:50 PM IST 
//


package com.mymortgagaeapp.data.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="mortgageApplication" type="{http://mymortgageapp.com/mortgageApplications}MortgageApplication"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mortgageApplication"
})
@XmlRootElement(name = "CreateOrUpdateApplicationResponse")
public class CreateOrUpdateApplicationResponse {

    @XmlElement(required = true)
    protected MortgageApplication mortgageApplication;

    /**
     * Gets the value of the mortgageApplication property.
     * 
     * @return
     *     possible object is
     *     {@link MortgageApplication }
     *     
     */
    public MortgageApplication getMortgageApplication() {
        return mortgageApplication;
    }

    /**
     * Sets the value of the mortgageApplication property.
     * 
     * @param value
     *     allowed object is
     *     {@link MortgageApplication }
     *     
     */
    public void setMortgageApplication(MortgageApplication value) {
        this.mortgageApplication = value;
    }

}
